### ISSUE TITLE
Recently purchased eBay CH341A adapter uses 0x1a86 0x5523

### ISSUE THREAD

**Issue by HattonLe** [John-sanpe/openocd-ch341a-patch#1]
Hi,
I came across openocd and decided to try it out as an alternative to program my Xess XSA-3S board. Luckily I found your project.
Eventually after figuring out how to configure openocd I realised that my adapter was coming back with a different USB ID.
0x1a86 0x5523

I patched my ch341a.cfg file and also the .c file and it now connects to it (I've not yet connected the JTAG to my FPGA board).

The Adapter board looks like this (I took off the USB A plug)
![20240424_072412](https://github.com/JohnSanpe/openocd-ch341a-patch/assets/17553260/24a0216f-8ab7-49ce-bb1d-1c8a551cf071)

**Comment by emhlb** [comment]
Thanks for raising this!
You actually need to move the jumper onto I2C/SPI, just like the image on README.

![e58c1668adda3754cedfeb29dd125c27](https://github.com/JohnSanpe/openocd-ch341a-patch/assets/33768314/d17eaec2-fa4d-4bdc-9cbc-fa7e874aaed7)

CH341A has three booting modes, which are determined by the jumper cap on the board, they will provide different functions.

![CH341A](https://github.com/JohnSanpe/openocd-ch341a-patch/assets/33768314/3cb0878a-8fd9-45cd-8ff7-3516d99cdab1)

[CH341A Datasheet](https://github.com/JohnSanpe/openocd-ch341a-patch/files/15148202/WCH.CH341A.-.Datasheet.pdf)
